# Generated by Django 4.0.4 on 2022-08-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='seleccion',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=100, null=True),
        ),
    ]
