# Generated by Django 4.0.4 on 2022-08-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apparm', '0002_proveedor_direccion_alter_proveedor_seleccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='seleccion',
        ),
    ]
