# Generated by Django 4.0.4 on 2022-09-19 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apparm', '0004_call_alter_proveedor_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='situation',
            new_name='Situation',
        ),
    ]
