# Generated by Django 4.0.4 on 2022-09-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparm', '0005_rename_situation_call_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='option',
            field=models.CharField(choices=[('Me paso a mi', 'Me paso a mi'), ('Ya era asi', 'Ya era asi')], max_length=100),
        ),
    ]
