# Generated by Django 4.0.4 on 2022-09-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparm', '0006_alter_call_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='terms',
            field=models.BooleanField(verbose_name='Tienes esta responsabilidad'),
        ),
    ]
